// <auto-generated />
namespace ARMeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Changebooktablemigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changebooktablemigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202202250623037_Change book table migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
